export {default as Home} from './home/Home'
export {default as Register} from './register/Register'
export {default as Login} from './login/Login'
export {default as AboutUs} from './about/aboutUs/AboutUs'
export {default as Team} from './about/team/Team'
export {default as Advisory} from './about/advisory/Advisory'
export {default as Advertise} from './about/advertiseWithUs/Advertise'
export {default as ContactUs} from './about/contactUs/ContactUs'
export {default as News} from './news/News'
export {default as CityProfile} from './cityProfile/CityProfile'
export {default as EditorsBlog} from './opinion/editorsBlog/EditorsBlog'
export {default as Opinions} from './opinion/opinions/Opinions'
export {default as SpecialReport} from './specialReport/SpecialReport'

export {default as Research} from './research/Research'
export {default as Webinars} from './research/webinars/Webinars'
export {default as WhitePaper} from './research/whitePaper/WhitePaper'
export {default as Trend} from './research/trend/Trend'


export {default as NewsDetails} from './newsDetails/NewsDetails'
export {default as TokenReward} from './tokenReward/TokenReward'